"""I/O boundary contracts for the MIST.AI backend.

These Protocol classes define the interfaces for external dependencies
(graph database, embeddings, LLM, event store) so that concrete
implementations can be swapped for test doubles via dependency injection.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from backend.knowledge.models import DocumentChunk, VectorSearchResult


class GraphConnection(Protocol):
    """Contract for Neo4j graph database access."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def execute_query(self, query: str, params: dict | None = None) -> list[dict]: ...
    def execute_write(self, query: str, params: dict | None = None) -> list[dict]: ...


class EmbeddingProvider(Protocol):
    """Contract for text embedding generation."""

    def generate_embedding(self, text: str) -> list[float]: ...
    def generate_embeddings(self, texts: list[str]) -> list[list[float]]: ...


class LLMProvider(Protocol):
    """Contract for large language model inference."""

    async def ainvoke(self, messages: list) -> Any: ...


class EventStoreProvider(Protocol):
    """Contract for conversation event storage."""

    def initialize(self) -> None: ...
    def start_session(self, input_modality: str = "voice") -> str: ...
    def end_session(self, session_id: str) -> None: ...
    def append_turn(self, event: Any) -> str: ...
    def get_turns(self, session_id: str) -> list: ...
    def get_turns_since(self, since: datetime) -> list[dict]: ...


class VectorStoreProvider(Protocol):
    """Contract for vector similarity search and chunk storage."""

    def store_chunks(self, chunks: list[DocumentChunk]) -> list[str]: ...
    def search(
        self,
        query_embedding: list[float],
        limit: int,
        filters: dict | None = None,
    ) -> list[VectorSearchResult]: ...
    def delete_by_source(self, source_id: str) -> int: ...
    def get_chunk(self, chunk_id: str) -> DocumentChunk | None: ...
    def count(self) -> int: ...
    def health_check(self) -> bool: ...
